### ISSUE TITLE
intel gen 10 igpu not work

### ISSUE THREAD

**Issue by resticDOG** [my33love/gk41-pve-ovmf#1]
你好! 我的CPU是i5 10400, pve版本6.3, 看资料说10代GPU不支持传统启动, 必须uefi, 用了你的文件, 同样是pve6.3版本, 但是hdmi一直没信号, 想问下你的romfile在哪找的, 是我的配置不对吗:
```conf
args: -set device.hostpci0.addr=02.0 -set device.hostpci0.x-igd-gms=1  -set device.hostpci0.x-igd-opregion=on
bios: ovmf
boot: order=sata0;ide2;net0
cores: 6
cpu: host
efidisk0: local-lvm:vm-100-disk-1,size=4M
hostpci0: 00:02.0,legacy-igd=1,romfile=igd.rom
ide2: local:iso/cn_windows_10_business_editions_version_20h2_updated_dec_2020_x64_dvd_547eb680.iso,media=cdrom
memory: 4096
name: win
net0: e1000=72:F7:34:8C:15:C5,bridge=vmbr0,firewall=1
numa: 0
ostype: win10
sata0: local-lvm:vm-100-disk-0,size=32G
scsihw: virtio-scsi-pci
smbios1: uuid=799fbb12-9c0a-4d3a-b304-fde0393283d3
sockets: 1
vga: none
vmgenid: 4cef19d9-2860-4751-89c5-d83467139fab
```

**Comment by my33love** [comment]
igd.rom是虚拟的rom不挑机型，并不是真的VBIOS，所以不同机型都是同一个文件。只是需要你去提取gop与vbt替换OVMF文件，这个一般要找对应自己机器的BIOS升级文件提取，提取后用UEFItool替换！

**Comment by resticDOG** [comment]
@my33love 我现在用[这个项目](https://github.com/patmagauran/i915ovmfPkg)编译出的romfile, 然后加上上面的配置hdmi可以显示ubuntu的安装界面了, 但是bios的界面还是没法显示, 安装完ubuntu之后倒是可以使用, 正常驱动, win10的话是一点都有显示, 我的主板bios不知是否可以提取你说的两个文件, 因为板载是没有cpu的, 并不是集成cpu的主板不知是否含有vbios固件.

**Comment by resticDOG** [comment]
使用[projectacrn](https://projectacrn.github.io/latest/tutorials/gpu-passthru.html#supported-hardware-platform)的方法编译提取出的GOP driver 和 VBT， 替换掉pve的ovmf bios之后hdmi还是无信号输出

**Comment by my33love** [comment]
[For Coffeelake and Cometlake iGPUs ](https://mega.nz/file/uYtnUSTJ#fPlR2Nq0_wAc9GO-TVzNPCmV4uRtF2wVcIb1Zw35WR4)。不是板载CPU，可能仅能提取到VBT，可以试着用下载的gop+你提取的vbt替换我编译后的ovmf文件再测试。projectacrn与pve-edk2并不完全一致，提取注入代码要一些技巧，所以最简单的就是直接替换，不用编译！

**Comment by resticDOG** [comment]
## 最新进展
 先用vnc uefi装完系统后, 开启RDP远程, 添加以上参数直通显卡, 可以正常boot到系统, 但是hdmi无信号输出, 远程之后可以正常安装核显驱动和识别核显, 但是同样黑屏无信号, 折腾了快两周了, 已经放弃了, 也不是有很大需求, 就是为了折腾, 分享下我的做法:
- 使用WIN10 LTSB 镜像
- 创建虚拟机 -> bios选OVMF, 机器I440X, 硬盘IDE, VGA默认, 网卡E1000, 创建之后直接开启虚拟机安装系统
- 打开RDP, 确认远程可以连接
- 关闭win10, 编辑配置文件
```bash
vim /etc/pve/qemu-server/100.conf
```
- 添加`args: -set device.hostpci0.addr=02.0 -set device.hostpci0.x-igd-gms=1  -set device.hostpci0.x-igd-opregion=on`, `hostpci0: 00:02.0,legacy-igd=1,romfile=igd.rom`两行配置
- 开机之后RDP远程进入安装Intel 核显驱动

以上可以正常使用RDP远程, 开启remotefx也能调用核显, 此方案算是我用过最成功的一种方案了, 另外一提: Ubuntu Desktop可以正常boot, hdmi正常输出画面.
bios还是没有显示, 不只是不是和10代GPU不支持传统启动有关. 还是感谢大佬, 我关掉这个issue了, 希望给后续研究的小伙伴提供一个思路.
