### ISSUE TITLE
Are Chrome and Electron based apps crashing?

### ISSUE THREAD

**Issue by vivekmiyani** [my33love/gk41-pve-ovmf#2]
Chrome and Electron based apps are crashing for me.
I have not used your driver tho instead used [this](https://github.com/patmagauran/i915ovmfPkg).
I just want to figure out if this happens to you also?

I created issue in [acidanthera](https://github.com/acidanthera/bugtracker/issues/1480) and also a [reddit](https://www.reddit.com/r/hackintosh/comments/kzz2j7/chrome_and_electron_based_apps_crashing_in_fully/) post.

If you have any solution please write!

Thanks in advanced :wink:!!

**Comment by zncs520** [comment]
chrome不会卡了,这个方案很好哦!!!完美!!
